proj_dir: /home/yunzliu/sgprocess
out_dir: /data/yunzliu/results/guide_extraction/kmer_check/k15
log_dir: /data/yunzliu/logs/guide_extraction/kmer_check/k15
work_dir: /data/yunzliu/tmp/guide_extraction_kmer_check_k15

guide_extraction:
  method: simpleaf

references:
  guide_csv: /data/yunzliu/references/raw_guides_k562_essential.csv
  guide_fasta: /data/yunzliu/references/guides_fixed.fasta
  guide_hash: /data/yunzliu/references/guide_hash_v3.pkl
  guide_t2g_2col: /data/yunzliu/references/t2g_2col_guide.tsv
  sgRNA_index_dir: /data/yunzliu/simpleaf_index_k15m11

simpleaf:
  conda_env: simpleaf
  bin_dir: /home/yunzliu/software/miniconda3/envs/simpleaf/bin
  af_home: /home/yunzliu/software/miniconda3/envs/simpleaf/opt/alevin-fry
  index:
    kmer_length: 15
    minimizer_length: 11
  quant:
    chemistry: 10xv3
    resolution: parsimony-gene

preprocess:
  trimmed: false
whitelist:
  min_umi: 1000
  min_genes: 500
resources:
  default_threads: 8
  simpleaf_index_threads: 4
  simpleaf_quant_threads: 12
  hash_quant_threads: 4
snakemake:
  latency_wait: 60
  rerun_triggers:
  - mtime
  - params
  - input
  - software-env
  - code
