proj_dir: /home/yunzliu/guide_extraction
out_dir: /data/yunzliu/results/guide_extraction/simpleaf_k13m9
log_dir: /data/yunzliu/logs/guide_extraction/simpleaf_k13m9
work_dir: /data/yunzliu/tmp/simpleaf_k13m9

guide_extraction:
  method: simpleaf

references:
  guide_csv: /data/yunzliu/references/raw_guides_k562_essential.csv
  guide_fasta: /data/yunzliu/references/guides.fasta
  guide_hash: /data/yunzliu/references/guide_hash_v3.pkl
  guide_t2g_2col: /data/yunzliu/references/t2g_2col_guide.tsv
  sgRNA_index_dir: /data/yunzliu/simpleaf_index_k13

simpleaf:
  conda_env: simpleaf
  bin_dir: /home/yunzliu/software/miniconda3/envs/simpleaf/bin
  af_home: /home/yunzliu/software/miniconda3/envs/simpleaf/opt/alevin-fry
  index:
    kmer_length: 13
    minimizer_length: 9
  quant:
    chemistry: 10xv3
    resolution: parsimony-gene

hash_matcher:
  window_start: 28
  window_end: 54
  guide_length: 20
  cb_prefix_len: 6
  umi_threshold: 1

preprocess:
  trimmed: false
whitelist:
  min_umi: 1000
  min_genes: 500
resources:
  default_threads: 8
  simpleaf_index_threads: 4
  simpleaf_quant_threads: 4
  hash_quant_threads: 4
snakemake:
  latency_wait: 60
  rerun_triggers:
    - mtime
    - params
    - input
